service:
  name: ${file(../../../../package.json ):name}-public-api-products

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation
  - serverless-plugin-resource-tagging
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
provider:
  name: aws
  stackTags:
    'Vugo Environment': 'Vugo'
  apiVersion: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):apiVersion}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Stage env for backend development, dev env for app users testing, production for released version
  region: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):region}
  role: ${self:custom.iamRole}
  deploymentBucket:
    name: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):srcBucketName}
    serverSideEncryption: AES256
  environment:
    STAGE: ${self:provider.stage}
    S3_BUCKET_NAME:  ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):assetBucketName}
  apiGateway: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicApiGateway}
  tags:
    apiVersion: ${self:provider.apiVersion}
  versionFunctions: false

functions:
  get-products:
    handler: product.getAllProducts
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/products
          cors: true
          documentation:
            summary: 'Get all Products'
            description: 'Get all Products'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Product data'
  get-active-products:
    handler: product.getAllActiveProducts
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/products/active
          cors: true
          documentation:
            summary: 'Get all Active Products'
            description: 'Get all Active Products'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Active Product data'   
  purchase-products:
    handler: product.purchaseProduct
    events:
      - http:
          method: post
          path: ${self:custom.publicBaseUrl}/products/{productId}/purchase
          cors: true
          documentation:
            summary: 'Purchase all Active Products'
            description: 'Purchase all Active Products'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Purchased Product data'   
custom:
  iamRole: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicIamRole}
  publicBaseUrl: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicBaseUrl}
  serverless-offline:
    port: 4000
  dotenv:
    path: ../../../../.env 
    basePath: ./
    logging: false
