service:
  name: ${file(../../../../package.json ):name}-admin-api-layouts

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation
  - serverless-plugin-resource-tagging
  - serverless-dotenv-plugin
provider:
  name: aws
  stackTags:
    'Vugo Environment': 'Vugo'
  apiVersion: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):apiVersion}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Stage env for backend development, dev env for app users testing, production for released version
  region: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):region}
  role: ${self:custom.iamRole}
  environment:
    STAGE: ${self:provider.stage}
    S3_BUCKET_NAME:  ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):assetBucketName}
  deploymentBucket:
    name: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):srcBucketName}
  apiGateway: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):adminApiGateway}
  tags:
    apiVersion: ${self:provider.apiVersion}
  versionFunctions: false

functions:
  layouts:
    handler: layout.getLayoutRails
    events:
      - http:
          method: get
          path: ${self:custom.adminBaseUrl}/layout/{page}
          cors: true
          documentation:
            summary: 'Get the page type and page rails'
            description: 'Get the page type and page rails'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Page type and Page rails'
  layout-rails-post:
    handler: layout.upsertPage
    events:
      - http:
          method: post
          path: ${self:custom.adminBaseUrl}/layout/{page}
          cors: true
          documentation:
            summary: 'Add Page Type'
            description: 'Add page type'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Page type'
  update-rails:
    handler: layout.postRailTitles
    events:
      - http:
          method: post
          path: ${self:custom.adminBaseUrl}/layout/rails/{railId}
          cors: true
          documentation:
            summary: 'Update Page Rail'
            description: 'Update page Rail'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Updated Page Rail'
  get-rails-details:
    handler: layout.getRailTitles
    events:
      - http:
          method: get
          path: ${self:custom.adminBaseUrl}/layout/rails/{railId}
          cors: true
          documentation:
            summary: 'Get Page Rail Details'
            description: 'Get page Rail Details'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Page Rail Details'
  get-rails-types:
    handler: layout.getAllRailTypes
    events:
      - http:
          method: get
          path: ${self:custom.adminBaseUrl}/layout/rail-types
          cors: true
          documentation:
            summary: 'Get Page Rail Types'
            description: 'Get page Rail Types'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Page Rail Types'   
custom:
  iamRole: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):adminIamRole}
  adminBaseUrl: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):adminBaseUrl}
  serverless-offline:
    port: 4000
  dotenv:
    path: ../../../../.env 
    basePath: ./
    logging: false