service:
  name: ${file(../../../../package.json ):name}-public-api-videos

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation
  - serverless-plugin-resource-tagging
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
provider:
  name: aws
  stackTags:
    'Vugo Environment': 'Vugo'
  apiVersion: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):apiVersion}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Stage env for backend development, dev env for app users testing, production for released version
  region: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):region}
  role: ${self:custom.iamRole}
  deploymentBucket:
    name: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):srcBucketName}
    serverSideEncryption: AES256
  environment:
    STAGE: ${self:provider.stage}
    S3_BUCKET_NAME:  ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):assetBucketName}
  apiGateway: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicApiGateway}
  tags:
    apiVersion: ${self:provider.apiVersion}
  versionFunctions: false

functions:
  list-videos:
    handler: video.listHandler
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/videos
          cors: true
          documentation:
            summary: 'get the list of videos'
            description: 'get the list of videos'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'The list of videos metadata'
  get-video-by-id:
    handler: video.getByIdHandler
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/videos/{videoId}
          cors: true
          documentation:
            summary: 'get a video by id'
            description: 'get a video by id'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'The video metadata'
  get-title-groups:
    handler: video.getTitleGroupsHandler
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/videos/groups
          cors: true
          documentation:
            summary: 'get all title groups'
            description: 'get all title groups'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'All title groups'
  get-title-group-by-id:
    handler: video.getTitleGroupByIdHandler
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/videos/groups/{groupId}
          cors: true
          documentation:
            summary: 'get a title group by id'
            description: 'get a title group by id'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'a title group'
custom:
  iamRole: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicIamRole}
  publicBaseUrl: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicBaseUrl}
  serverless-offline:
    port: 4000
  dotenv:
    path: ../../../../.env 
    basePath: ./
    logging: false
