service:
  name: ${file(../../../../package.json ):name}-public-api-locations

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation
  - serverless-plugin-resource-tagging
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
provider:
  name: aws
  stackTags:
    'Vugo Environment': 'Vugo'
  apiVersion: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):apiVersion}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} # Stage env for backend development, dev env for app users testing, production for released version
  region: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):region}
  role: ${self:custom.iamRole}
  deploymentBucket:
    name: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):srcBucketName}
    serverSideEncryption: AES256
  environment:
    STAGE: ${self:provider.stage}
    S3_BUCKET_NAME:  ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):assetBucketName}
  apiGateway: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicApiGateway}
  tags:
    apiVersion: ${self:provider.apiVersion}
  versionFunctions: false

functions:
  get-geofence:
    handler: location.getGeoFence
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/locations/geo-fencing
          cors: true
          documentation:
            summary: 'Get GeoFence'
            description: 'Get GepFence'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains GeoFence Details'
  get-whitelisted-ip:
    handler: location.getWhiteListedIp
    events:
      - http:
          method: get
          path: ${self:custom.publicBaseUrl}/locations/white-listed-ips
          cors: true
          documentation:
            summary: 'Get Whitelisted Ips'
            description: 'Get Whitelisted Ips'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains Whitelisted Ip Details'
  is-in-valid-zone-or-ip:
    handler: location.inInValidZoneOrIp
    events:
      - http:
          method: post
          path: ${self:custom.publicBaseUrl}/locations/check
          cors: true
          documentation:
            summary: 'Check Zone or IP'
            description: 'Check Zone or IP'
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Response contains IsActive'   
custom:
  iamRole: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicIamRole}
  publicBaseUrl: ${file(../../../../deploymentConfig/config.${self:provider.stage}.yml):publicBaseUrl}
  serverless-offline:
    port: 4000
  dotenv:
    path: ../../../../.env 
    basePath: ./
    logging: false
